### ISSUE TITLE
Use Localized Names from Angel's Industries for Casting Recipes

### ISSUE THREAD

**Issue by Recon419A** [Pezzawinkle/PezsMods#12]
Currently, all casting recipes localize as something like "Die Casting of Angels-Gear." Ideally, they would localize more like "Die Casting of Gear," but even this has its issues (as it really should be "Die Casting of Gears"). As I see it, we have several options to fix this:
1) Copy the design pattern used in Angel's mods, where better tiers of casting aren't differentiated in the localizations - that is, "Die Casting of Angels-Gear" and "Sand Casting of Angels-Gear" would simply be renamed to "Gear" by removing the localization and setting `main_product = angels-gear`. The main advantage of this approach is that it shifts the burden of localization entirely onto Angel's mods and allows us to take advantage of translations and localization fixes transparently. This method would also "look and feel" consistent with recipes in vanilla Angel's for things like coolant casting that don't have special names.
2) Find some way to inline the Angel's localizations in the middle of our dynamic localization: that is, make it so we do a lookup and "Die Casting of Angels-Gear" becomes more akin to "Die Casting of $LOCALIZATION(angels-gear)." In this case, that would translate to "Die Casting of Gear." The main advantage of this approach is that it allows us to use customized localizations for our casting methods, but the main disadvantage is that we can't use plurals for things that should ordinarily be pluralized - that is, we have "Die Casting of Gear" or "Die Casting of Axle" instead of "Die Casting of Gears" or "Die Casting of Axles".
3) Write custom localizations for each recipe individually. This is the most flexible, and isn't really that much work, but it is brittle and prone to typos. That being said, we would already have to add things to an intermediates table in order to add them to the mod, so we could do this without adding much overhead. The real disadvantage here is that we wouldn't be able to take advantage of translations done for Angel's mods - we'd have to translate (or copy translations of) everything ourselves.

**Comment by Recon419A** [comment]
Personally, I lean towards the first option because it's the least work for us and produces the most similar look and feel to vanilla Angel's, but I want to hear from the other maintainers.

**Comment by Pezzawinkle** [comment]
i know there is a way to do #2, i can take a look at that, i think its a nested lookup so something like
`localised_name={"recipe-name.die-casting",{"item-name.",blah}}`
from memory, this should do the correct lookup from angels locale, ill test that today

**Comment by Pezzawinkle** [comment]
fixed as part of commit: bdbad64

**Comment by Recon419A** [comment]
Does `bdbad64` fix this for all intermediates, or just for gears and mechanical parts?
