### ISSUE TITLE
Item/Recipe icons are swapped

### ISSUE THREAD

**Issue by kirazy** [Pezzawinkle/PezsMods#13]
Items:
`ASE-sand-die`
`ASE-metal-die`

These two items/recipes are using the icon intended for the other.

You also want to use `scale = 0.4375` and `shift = {-10, -10}` for the small icon overlays for recipes to match with Angel's scaling/positioning.

**Comment by kirazy** [comment]
```LUA
-- Fix ASE-sand-die and ASE-metal-die
data.raw.item["ASE-sand-die"].icons = {{
    icon = "__angelssmelting__/graphics/icons/expendable-mold.png",
    icon_size = 32,
    icon_mipmaps = 1,
}}

data.raw.item["ASE-metal-die"].icons = {{
    icon = "__angelssmelting__/graphics/icons/non-expendable-mold.png",
    icon_size = 32,
    icon_mipmaps = 1,
}}
```

This is how I fixed them in my mod.

**Comment by Pezzawinkle** [comment]
so the "items" are using the "recipe" icons, and visa versa?
ok, now i get you :D
