### ISSUE TITLE
Recipe for tier 2 bronze coil is wrong

### ISSUE THREAD

**Issue by adamcirillo** [Pezzawinkle/PezsMods#2]
see screenshot also seems to effect other tier sheet coils

![image](https://user-images.githubusercontent.com/13363284/80302519-dc39dd00-87ed-11ea-8564-1526066129d5.png)

**Comment by Pezzawinkle** [comment]
should be fixed with the latest update
i was not copying the ingredient from recipe 1 to 2 correctly for the non tungsten recipe
