### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by KiwiHawk** [Pezzawinkle/PezsMods#20]
![image](https://github.com/Pezzawinkle/PezsMods/assets/59639/4e00324f-62f6-4e40-a999-5e06e8622b50)

Mod list:
- angels-smelting-extended
- angelspetrochem
- angelsrefining
- angelssmelting
- bobelectronics
- boblibrary

**Comment by Pezzawinkle** [comment]
I have fixed the issue, it was incorrectly checking for insulated wire which is created at that stage in data, i have not linked it with the trigger for tin wire as appropriately found in angels smelting.
