### ISSUE TITLE
Error after update to nwe angels version

### ISSUE THREAD

**Issue by Ldmf** [Pezzawinkle/PezsMods#3]
after updating angels mods

![20200820183906_1](https://user-images.githubusercontent.com/15316448/90800161-9234b400-e314-11ea-95ae-a07382ff4c80.jpg)

**Comment by Pezzawinkle** [comment]
This should be fixed in the latest release. Sorry for the delay, i have had this fixed in dev for a while now

**Comment by Ldmf** [comment]
Ok no Problem and thx for the work
