### ISSUE TITLE
Write a README

### ISSUE THREAD

**Issue by Recon419A** [Pezzawinkle/PezsMods#8]
Currently, the project has no README; one should be added. Low priority, but touching this up with a nice README that includes images and descriptions of the mod's functionality could also serve to provide a more detailed page for the mod portal as well.

**Comment by Pezzawinkle** [comment]
I will get onto that, i guess its been something i never got around to, especially since it was just me for soo long.

**Comment by Pezzawinkle** [comment]
I hope that the initial version is to your liking... not sure if i want to add images to it though.
