### ISSUE TITLE
Fix Icons/Localisations/Recipes for Angel's Gears and Mechanical Parts

### ISSUE THREAD

**Issue by Recon419A** [Pezzawinkle/PezsMods#9]
In component mode, Angel's gears cannot be cast directly; however, the sand-casting and die-casting recipes for mechanical parts show the gear icon instead, and the localization also reads as producing gears (carried over from the non-components mode). This just needs to be touched up to have proper recipes, localization, and iconography.

**Comment by Recon419A** [comment]
I'm not sure whether I'll get to this today, but if not it will be in the first half of this upcoming week.

**Comment by Recon419A** [comment]
This is a little more complicated than I originally thought. The existing deep copy structure that bases everything on iron gears needs to be fully rewritten because iron gears don't exist at all in component overhaul and they get replaced by mechanical parts (not gears) by Angel's Industries. I'll need to write some functions and recode a significant chunk of ironworks.lua, so this'll likely take me a few days.

**Comment by Pezzawinkle** [comment]
Unless that was changed, the replacement should be just the item, not the name, the original recipe should still "exist", but be hidden and have the newer parts.
Im pretty sure i set the angels industries replacement script in data-final-fixes, not data-updates... so it should still be gears when the script runs, unless i/we got that wrong?
